### ISSUE TITLE
Table extension does not recognize tables that have any empty header cells

### ISSUE THREAD

**Issue by Monkatraz** [lezer-parser/markdown#1]
![image](https://user-images.githubusercontent.com/34875062/107585575-c0a49500-6bbb-11eb-8bb3-35616c5389d0.png)
![image](https://user-images.githubusercontent.com/34875062/107585598-cd28ed80-6bbb-11eb-8da1-9c90ca102470.png)

As far as I know, this is valid syntax for GFM tables. Well, actually, I can prove it!

|  |  |  |
| -- | -- | -- |
| see ma | no | headers |

Just to demonstrate real-world use: with the right styling, using this lets you get simple unmarked tables:
![image](https://user-images.githubusercontent.com/34875062/107585956-52ac9d80-6bbc-11eb-9fd1-8bd5ec38fb35.png)

Great work on the extension support btw, its API is so much cleaner than `markdown-it` and natively supports more complex syntax. In particular, multi-character delimiters I've found very easy to add. I will absolutely attempt to make an HTML renderer for it.

EDIT: Hah, I just took a look at the GFM spec and it doesn't even mention this edge case. Don't you love Markdown?

**Comment by marijnh** [comment]
I was wondering about that when implementing it, but since the GFM docs don't mention it at all, I figured no one did that.

To be fair, the CommonMark spec itself is a _lot_ more precise than the GFM extensions (which leave just about every corner case unspecified).
