### ISSUE TITLE
Duplicate re-parsing when inserting an empty list item?

### ISSUE THREAD

**Issue by craftzdog** [lezer-parser/markdown#10]
Hi! I'd like to ask a question about the Markdown block parser.
Say you have the below Markdown (`|` represents the current cursor position):

    * List item|
    
    ```js
    function foo() {
      return false
    }
    ```

When inserting a new list item by hitting <kbd>Enter</kbd> key:

    * List item
    * |
    
    ```js
    function foo() {
      return false
    }
    ```

The JS codeblock after the list gets re-parsed. I could see the JavaScript parser running again.
Could you tell me why it happens? If we could avoid that, it would greatly improve performance.

**Comment by marijnh** [comment]
That was a bug in the way tree fragments going all the way up to the end of the document were handled—it only happened if there was no further content after the code block. Attached patch should fix it.
