### ISSUE TITLE
Some browsers can't catch SyntaxError in regexp at runtime

### ISSUE THREAD

**Issue by Danon** [lezer-parser/markdown#13]
In `markdown.ts`, on line 1357 there's this code:

```
let Punctuation = /[!"#$%&'()*+,\-.\/:;<=>?@\[\\\]^_`{|}~\xA1\u2010-\u2027]/;
try { 
  Punctuation = /[\p{Pc}|\p{Pd}|\p{Pe}|\p{Pf}|\p{Pi}|\p{Po}|\p{Ps}]/u 
} catch (_) {
}
```

I understand that it's supposed to provide some form of default punctuation regexp, and if it's supported, then use this `\p` notation. `\p` is supported in browsers since Ecma2018, but I see you also want to support older browsers, because you provide the alternative notation without the `\p`, and to do that you use `try`/`catch`, which is supposed to catch `SyntaxError`, and it actually works, **on some browsers**.

Some browsers parse it in runtime, throw the exception and can catch them. This is also how node.js works. But other browsers, some based on FireFox engine, are actually parsing the regexp in compile time, and the `catch` simply doesn't catch them. It's as if the JavaScript parsing fails on them.

The fix could be very easy, simply write it as:
```
try { 
  Punctuation = new RegExp('[\\p{Pc}|\\p{Pd}|\\p{Pe}|\\p{Pf}|\\p{Pi}|\\p{Po}|\\p{Ps}]', 'u');
} catch (_) {
}
```
And in that case it's *guranteed* to be parsed at runtime, which means any `SyntaxError` thrown will be cought by the `catch`. The example of browser that don't work with that is for example SeaMonkey.

![image](https://user-images.githubusercontent.com/13367735/151794203-b3c18506-d354-4175-8759-0b02c0068a36.png)

This fix would have to be done everywhere, of course, where unsupported tokens with `/u` flag are used; but I only found this one.

**Comment by marijnh** [comment]
Thanks for spotting that. That should indeed use `new RegExp`

**Comment by Danon** [comment]
@marijnh Cause I have users that use older browsers and the app crashes for them. I have no way of surpressing the exception in their browser cause their `catch ()` doesn't catch the `SyntaxError` :/

**Comment by marijnh** [comment]
Thanks for confirming. Tagged as 0.15.4

**Comment by Danon** [comment]
No problem thanks.

When do you think the @codemirror/lang-markdown can get a proper release with this update?

**Comment by Danon** [comment]
You're right, my bad. Sorry for wasting your time on this ;D
