### ISSUE TITLE
Table extension does not follow GFM spec (cannot interrupt a paragraph)

### ISSUE THREAD

**Issue by acnebs** [lezer-parser/markdown#15]
In the [GFM](https://github.github.com/gfm/) spec, all `leaf` blocks are allowed to interrupt a paragraph, for example a fenced code block can appear in the text immediately after other text with no line breaks, like so:
```js
const x = 3
```

And this markdown parser respects that part of the spec. However, I've noticed that the Table extension provided by the lib does *not* follow this convention, and if a Table interrupts a paragraph lezer does not recognize it as such.

Easiest way to demonstrate is probably that Github's markdown parser, which follows the spec exactly AFAIK, allows this behavior, like so:
| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |

Anyway just thought I'd point this out, thanks for making such a cool parsing library!

**Comment by acnebs** [comment]
Thanks @marijnh, looks great! Would you mind tagging this as a new version?

**Comment by marijnh** [comment]
Sure -- done

**Comment by acnebs** [comment]
Awesome, thank you. I think @codemirror/lang-markdown might need to be bumped too though, as I'm now seeing some type incompatibilities between the two (specifically around the `MarkdownExtension` type).

**Comment by marijnh** [comment]
No, just reinstall your dependencies to force npm to properly deduplicate them (it has an issue where upgrading will often inappropriately install multiple versions of a package).

**Comment by acnebs** [comment]
And finally – is there a reason why the methods like `scanLine` and `readLine` are marked as internal with typescript hints? I mean, I understand why in that if you used the `private` qualifier it would not be accessible to the built-in extension implementations (like `Table`) in `extensions.ts`, but personally I think it would be best if all of the built-in extensions used only the publicly accessible library API.
