### ISSUE TITLE
Some reference documentation is not updated

### ISSUE THREAD

**Issue by bxff** [lezer-parser/markdown#19]
Styles in `NodeSpec`, which are recently added, is not updated on the markdown reference documentation in the `README.md`.

https://github.com/lezer-parser/markdown/blob/3c5f5dc3b5be08e19c32f0f7fac6f3619a58c911/src/markdown.ts#L961-L966

**Comment by marijnh** [comment]
Attached patch regenerates the readme from the current sources.
