### ISSUE TITLE
The parse function in the BlockParser interface is missing the Line argument in the docs

### ISSUE THREAD

**Issue by Monkatraz** [lezer-parser/markdown#2]
The eager parser function in `BlockParser` seems to be documented incorrectly - in the readme, it shows that the function is only passed a context object, which does not expose enough information to actually do anything with. This is because, I assume unintentionally, the second argument passing a `Line` object is not shown in the documentation.

I assume it's supposed to be:
```ts
type EagerParser = (cx: BlockContext, line: Line) => boolean | null
```

**Comment by marijnh** [comment]
Thanks for spotting that!
