### ISSUE TITLE
The `line`-parameter in `BlockParser` `parse()`-methods should not be a side-effect

### ISSUE THREAD

**Issue by nathanlesage** [lezer-parser/markdown#20]
First of all, thank you for all the work you've already poured into CodeMirror 6. I'm currently migrating and I really like the cleaner and faster API.

However, while I am an absolute fan of the pure design of the system, I noticed one very awkward side-effect that the markdown package is producing. Specifically, one can define additional `BlockParser`s that define a `parse`-method which receives a `line`-parameter. A block parser is, as I've learned, expected to parse every line that belongs to the block and add corresponding tree elements to it _in one single go_.

At first, I was very confused since I only get a `line` object once and `nextLine()` only returns a boolean. It took me some time to realize that the `line` object magically updates after each call to `nextLine`. I just had a look, and indeed it's a class that updates itself on every call, not as one might think when [looking at the docs for the core package, an object](https://codemirror.net/docs/ref/#state.Line).

This feels very weird and out of place given the very pure and functional style of the whole ecosystem. Therefore, wouldn't it be cleaner or at least more transparent to users if `nextLine` would return a Line object or `undefined` instead of a boolean?

I do see the benefit of being able to write something like `while(ctx.nextLine() && line.text !== someCondition)` instead of always having to remember the line, but it does have its drawbacks.

An alternative would be to make it clear in the documentation that the `line` parameter is _not_ a Line object (as defined in the core library), but actually kind of an iterator. Maybe even rename that class? That would make the side effect a little bit more obvious.

A third alternative might be to move the Line class instance to the context object, since `ctx.line` makes it clearer that the context and the line are coupled.

What do you think? Thanks a bunch in advance! Sorry that I'm starting off with such a nitty-gritty issue 🙈

**Comment by marijnh** [comment]
The `Line` class you link to is a different one from the [one in the @lezer/markdown package](https://github.com/lezer-parser/markdown#----class----line).

As for whether it should be immutable, it's not, for efficiency reasons, and that's going to stay that way.

**Comment by nathanlesage** [comment]
Ah, I must've overseen that documentation, thank you for the pointer. Maybe I just need a better grip of the new module system.
