### ISSUE TITLE
More extensions: Insert and Mark

### ISSUE THREAD

**Issue by NH002** [lezer-parser/markdown#22]
I need extensions for [markdown-it-ins](https://github.com/markdown-it/markdown-it-ins) and [markdown-it-mark](https://github.com/markdown-it/markdown-it-mark). For **insert** extension we could use `inserted` tag, and add a new tag for **marked** (ideally to [lezer-parser/highlight](https://github.com/lezer-parser/highlight)).

I'm gonna implement this myself if I can, just opening this issue in case I need help.

**Comment by danon** [comment]
@NH002 That's cool feature. Did you manage to implement it?

**Comment by marijnh** [comment]
Going to close this as not really an issue report—ask here or on the forum if you do end up needing advice.

**Comment by NH002** [comment]
@danon Sadly not, I haven't got time. Though I'm still thinking about it I have no idea when will I be able to work on it.
