### ISSUE TITLE
Table parser does not create a TableCell element that is empty or only comprised of spaces/tabs.

### ISSUE THREAD

**Issue by mkraft** [lezer-parser/markdown#23]
https://github.com/lezer-parser/markdown/blob/a5f28b6611b149e3473c226e699c1f0b25239aa5/src/extension.ts#L50 skips blank spaces and tabs so the `TableCell` element isn't created.

**Comment by marijnh** [comment]
This is intentional. Why is it causing trouble for you?

**Comment by mkraft** [comment]
> This package has no functionality for emitting HTML, so I'm not sure what you mean by 'render' here.

What I mean is that because of the missing table cell a client isn't able to render correctly because they can't differentiate between, say:

```markdown
|foo|||
|--|--|--|
|bar|baz|
```
```markdown
||foo||
|--|--|--|
|bar|baz|
```
```markdown
|||foo|
|--|--|--|
|bar|baz|
```

**Comment by marijnh** [comment]
There are table separators in the tree. Again, what kind of client are you talking about?

**Comment by mkraft** [comment]
I was using it with a client that rendered the tree as HTML and was therefore missing the `<td>` elements in the header. Then I wrote a test 

https://github.com/lezer-parser/markdown/compare/main...mkraft:markdown:empty-header-cell

and believed that because it was failing the tree wasn't parsed as I would have expected.

Have I put two-and-two together incorrectly?

**Comment by marijnh** [comment]
I'd say this is an issue in the rendering code, which makes an incorrect assumption about the guaranteed presence of these nodes.

**Comment by mkraft** [comment]
Are you saying that the client can optionally interpret the presence of blank spaces via the index values? For example the difference how these are parsed:

```markdown
||b|c|\n|--|--|--|\n|1|2|3|\n
```
vs
```markdown
| |b|c|\n|--|--|--|\n|1|2|3|\n
```

```diff
TableHeader,  0,  6, 28, 
TableDelimiter,  0,  1,  8, 
-TableDelimiter,  1,  2, 12,
+TableDelimiter,  2,  3, 12,
...
```
