### ISSUE TITLE
Is removing language features possible?

### ISSUE THREAD

**Issue by acnebs** [lezer-parser/markdown#24]
Hi, I want to remove certain language features (namely setext-style headers) from parsing. Is this possible in an extensible way or will I need to modify the parser itself in order to do this? Had a look at the code but it wasn't clear to me if this is possible. Basically I want to do [this](https://github.com/codemirror/codemirror5/issues/6129) but for CM6.

Thanks!

**Comment by marijnh** [comment]
Yes, you can use the [`remove`](https://github.com/lezer-parser/markdown#user-content-markdownconfig.remove) extension field to remove parsers by name (in this case `"SetextHeading"`).

Please use the [forum](https://discuss.prosemirror.net) for questions, and this issue tracker for bugs.
