### ISSUE TITLE
Checklists/todos are highlighted as such without a trailing slash

### ISSUE THREAD

**Issue by acnebs** [lezer-parser/markdown#25]
[(Originally posted in CodeMirror issue tracker but figured here is better)](https://github.com/codemirror/dev/issues/1125)

In GFM, the task list syntax is like this:

```markdown
- [ ] my task item
```

Lezer's markdown language highlights this correctly, but it _also_ highlights this
```markdown
- [ ]my task item
```
Which [according to the spec](https://github.github.com/gfm/#task-list-items-extension-) is not a valid task list item, but is rather just a list item that starts with some [] characters.

You can see this in practice in GitHub's markdown renderer:

- [ ] this is a task
- [ ]this is not

Probably lezer's markdown parser should behave that way as well.

**Comment by acnebs** [comment]
I've gone ahead and [made a PR](https://github.com/lezer-parser/markdown/pull/26) (since this is a dead simple change) if you're happy with this @marijnh.

**Comment by marijnh** [comment]
I'm wondering if we might also want to parse lines with just `- [ ]` as tasks lists (not following the spec) in order to make this less confusing to people typing this in an editor. (This package is more about editor tooling than about fully correct Markdown parsing.)

**Comment by acnebs** [comment]
Yeah, I was thinking about that as well, and was a bit conflicted. On the one hand if the user actually follows through, it is less jarring for them if the task list is marked as such as soon as they type the closing bracket. However, it does seem desirable to highlight things according to the spec because otherwise it is slightly misleading. A user types - [ ], it is highlighted by lezer as a task list, but then when they actually throw that into basically any markdown renderer with GFM support, it will *not* be rendered as such.

**Comment by marijnh** [comment]
Guess it doesn't matter too much either way. I've merged the PR.

**Comment by acnebs** [comment]
Thanks!
