### ISSUE TITLE
Code block breaks when backticks are inside a property

### ISSUE THREAD

**Issue by danielv27** [lezer-parser/markdown#28]
When adding a description with the following form the back ticks around "main" break the code block causing everything after it to be rendered incorrectly.

````
```{caption="Code from function `main`"}
````

![image](https://github.com/lezer-parser/markdown/assets/70969597/10b5d64d-446d-4ed4-8a97-47e12c295680)

**Comment by marijnh** [comment]
This matches what the [CommonMark reference implementation](https://spec.commonmark.org/dingus/?text=%0A%60%60%60%7Bcaption%3D%22Code%20from%20function%20%60main%60%22%7D%0A**bold**%0A) does here, so I think the issue is with your expectations of how this should work.
