### ISSUE TITLE
Autolink fails for URLs with >3 parts in the domain

### ISSUE THREAD

**Issue by hubgit** [lezer-parser/markdown#29]
The `Autolink` extension seems to skip anything after the first 3 parts of a domain, e.g. `https://www.example.co.uk/`.

<img width="581" alt="image" src="https://github.com/lezer-parser/markdown/assets/14294/3ac19420-3863-4150-b15b-11a9cc082525">

[Demo in CodeSandbox](https://codesandbox.io/p/sandbox/codemirror-markdown-autolink-shsgd9)

The version of `@lezer/markdown` with the `Autolink` extension doesn't seem to be on Try yet, but [this example](https://codemirror.net/try/?c=aW1wb3J0IHsgYmFzaWNTZXR1cCwgRWRpdG9yVmlldyB9IGZyb20gImNvZGVtaXJyb3IiOwppbXBvcnQgeyBtYXJrZG93biwgbWFya2Rvd25MYW5ndWFnZSB9IGZyb20gIkBjb2RlbWlycm9yL2xhbmctbWFya2Rvd24iOwppbXBvcnQgeyBzeW50YXhIaWdobGlnaHRpbmcsIEhpZ2hsaWdodFN0eWxlIH0gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZ3VhZ2UiOwppbXBvcnQgeyBUYWcsIHN0eWxlVGFncyB9IGZyb20gIkBsZXplci9oaWdobGlnaHQiOwoKY29uc3QgdXJsVGFnID0gVGFnLmRlZmluZSgpOwoKbmV3IEVkaXRvclZpZXcoewogIGRvYzogInRlc3QgaHR0cHM6Ly93d3cuZXhhbXBsZS5jby51ay8gdGVzdCIsCiAgZXh0ZW5zaW9uczogWwogICAgYmFzaWNTZXR1cCwKICAgIG1hcmtkb3duKHsKICAgICAgYmFzZTogbWFya2Rvd25MYW5ndWFnZSwKICAgICAgZXh0ZW5zaW9uczogW3sgcHJvcHM6IFtzdHlsZVRhZ3MoeyBVUkw6IHVybFRhZyB9KV0gfV0sCiAgICB9KSwKICAgIHN5bnRheEhpZ2hsaWdodGluZyhIaWdobGlnaHRTdHlsZS5kZWZpbmUoW3sgdGFnOiB1cmxUYWcsIGNvbG9yOiAiYmx1ZSIgfV0pKSwKICBdLAogIHBhcmVudDogZG9jdW1lbnQuYm9keSwKfSk7Cg==) should in theory also illustrate the problem.

**Comment by marijnh** [comment]
That patch should help.

**Comment by hubgit** [comment]
It does!
