### ISSUE TITLE
Incorrect offset of children's children when using addElement in a BlockParser eager parser

### ISSUE THREAD

**Issue by Monkatraz** [lezer-parser/markdown#3]
Here is a representative example of my eager parser (`BlockParser['parser']`) code:
```ts
/** Returns a `MarkdownConfig` extension that adds a line-start based syntax using the given string.
 *  @example const ext = line('#', 'Heading1') */
function line(str: string, name: string, { interrupt, consume }: LineOpts): MarkdownConfig {

  const mark = name + 'Mark'
  const chars = toPoints(str)

  const parse = (cx: BlockContext, line: Line) => {
    if (matches(chars, line.pos, line)) {
      const start = cx.lineStart + line.pos
      const len = chars.length
      const offset = start + len

      // starting marker (e.g. '//' in a line comment)
      const children = [cx.elt(mark, start, offset)]
      if (!consume) children.push(...cx.parseInline(line.text.slice(len), offset))

      cx.nextLine()
      cx.addElement(cx.elt(name, start, cx.prevLineEnd(), children))

      return true
    }
    return false
  }

  return {
    defineNodes: [{ name, block: true }, mark],
    parseBlock: [{
      name,
      parse,
      endLeaf: !interrupt ? undefined : (_, line) => matches(chars, line.pos, line),
      before: 'Blockquote'
    }]
  }
}
```
The intention of this code is to generically support 'line' syntax, like ATX headings or JS line comments. 

The way this malfunctions is as following:
```ts
// this is added as an extension
const ext = line('//', 'LineComment', { interrupt: true })

// given the following input (truncated): 
/*
Markdown Test Page
***
// `inline code`
*/

// I get this in the tree:
/*
└─ Document [0..22192]
   ├─ Paragraph [0..18]: 'Markdown Test Page'
   ├─ HorizontalRule [19..22]: '***'
   ├─ LineComment [23..39]
   │  ├─ LineCommentMark [23..25]: '//'
   │  └─ InlineCode [26..39]
   │     ├─ CodeMark [75..76]: 'i'
   │     └─ CodeMark [87..88]: ''
*/
```

As you can probably see, the 'children's children' have incorrect offsets. I've done some poking around, and while I'm still not sure why this is happening, I am fairly confident that the issue is not within the `cx.inlineParse` function.

![image](https://user-images.githubusercontent.com/34875062/107729002-ce861300-6cac-11eb-896c-b290063ed4bc.png)

This is `console.log(children)`. To me, everything seems correct here - I think the issue is with `addElement`.

**Comment by marijnh** [comment]
> `if (!consume) children.push(...cx.parseInline(line.text.slice(len), offset))`

That seems like it should be `slice(line.pos + len)`.

But that doesn't seem to be the issue here—I was able to reproduce this, and attached patch should help.

**Comment by Monkatraz** [comment]
> That seems like it should be `slice(line.pos + len)`.
> 
> But that doesn't seem to be the issue here—I was able to reproduce this, and attached patch should help.

Thank you, nice catch.
