### ISSUE TITLE
Table folding not work

### ISSUE THREAD

**Issue by losingle** [lezer-parser/markdown#30]
<img width="285" alt="Screenshot 2023-11-04 at 03 58 33" src="https://github.com/lezer-parser/markdown/assets/540630/3544b93b-4f56-4e3f-aa69-467d3e0ec7e7">

---

Without loading GFM, the table can be folded.
But no header highlighting

<img width="266" alt="Screenshot 2023-11-04 at 04 02 34" src="https://github.com/lezer-parser/markdown/assets/540630/e55c7fca-4df8-4f0a-8ba1-50c63710966c">
<img width="252" alt="Screenshot 2023-11-04 at 04 02 19" src="https://github.com/lezer-parser/markdown/assets/540630/d2fb50ea-518b-425c-a44f-4bb8c9779f5a">

```javascript
markdown({
                    base: commonmarkLanguage,
                    addKeymap: true,
                    completeHTMLTags: true
                }),
```

**Comment by marijnh** [comment]
Attached patch should help with this.
