### ISSUE TITLE
Parser assumes that IndentedCode will not be disabled

### ISSUE THREAD

**Issue by Monkatraz** [lezer-parser/markdown#4]
Certain bits of `lezer-markdown` check for the indentation level because it may invalidate a block or whatever entity due to `IndentedCode` becoming valid.

e.g. in `BlockContext.advance`:
```ts
if (line.indent < line.baseIndent + 4) {
  for (let stop of parser.endLeafBlock) if (stop(this, line)) break lines
}
```

However, because you are allowed to disable `IndentedCode` (which I appreciate!), these checks should no longer run if `IndentedCode` is disabled, but that edge case isn't checked. At least, that's what I would think - I understand that this is basically an extendable CommonMark implementation, and that this is what the spec describes.

**Comment by marijnh** [comment]
I'm don't think that's the case—the CommonMark spec explicitly disables certain behavior when lines are indented more than 4 columns. That isn't necessarily related to indented code. For example the snippet you quote is about unconditionally continuing indented paragraph content—no actual code block is started for content like this...

```
First line
    indented continued
    lines
```

That's a single paragraph.

**Comment by Monkatraz** [comment]
> ```
> First line
>     indented continued
>     lines
> ```
> 
> That's a single paragraph.

I stand corrected. I'm also horrified.

**Comment by marijnh** [comment]
I have no idea what the reasoning behind such rules is. (I suspect they may even originate from bugs in Gruber's original reference parser.)
