### ISSUE TITLE
Custom tags for table elements

### ISSUE THREAD

**Issue by alex-titarenko** [lezer-parser/markdown#40]
It would be nice to have custom tags exported from the library for:
`Table`, `TableCell`, `TableHeader`, `TableRow`, `TableDelimiter`

If those new custom tags would be inherited from existing, it will be backward compatible with the existing code.

This functionality would allow to apply custom styling for table like make content as Monospace.

**Comment by marijnh** [comment]
It is possible to extend the parser to add your own tags to whichever nodes you want, so this is not something for which you need the base library to change. See the [`props`](https://github.com/lezer-parser/markdown#user-content-markdownconfig.props) property on Markdown extensions, which you can combine with [`styleTags`](https://lezer.codemirror.net/docs/ref/#highlight.styleTags).

**Comment by NotTimTam** [comment]
Considering that most are utilizing this library via @codemirror/lang-markdown, how would we extend the props to add these custom tags when applying this module via `markdownLanguage`?

Would I have to forego @codemirror/lang-markdown?

Thanks

**Comment by marijnh** [comment]
No, @codemirror/lang-markdown allows you to [pass in](https://github.com/codemirror/lang-markdown?tab=readme-ov-file#user-content-markdown^config.extensions) parser extensions as well.

**Comment by NotTimTam** [comment]
Sorry, I may not be fully aware of all the features. But because base is already set to markdownLang:
```js
markdown({
  base: markdownLanguage,
  codeLanguages: languages,
  extensions: [],
}),
```

When I try to pass a custom extension to handle tables, they don't get passed in to it because they've already been handled.

```js
import { tags } from "@codemirror/language";

const TableDelim = { resolve: "Table", mark: "Table" };

const Table = {
	defineNodes: ["Table", "TableMark"],
	parseInline: [
		{
			name: "Table",
			parse(cx, next, pos) {
				console.log(next);
			},
		},
	],
};
export default Table;

```

When I run this, I never see character 124 ("|")?

Could be my misunderstanding of the feature.

Sorry

**Comment by marijnh** [comment]
Yes, I wasn't recommending you pass in another extension that parses tables. I was recommending you use a `props` extension that adds extra style tags.
