### ISSUE TITLE
Interaction between emphasis and html tags is not CommonMark compliant

### ISSUE THREAD

**Issue by spencer246** [lezer-parser/markdown#44]
```markdown
**bold-**char**bold again**

**bold-**<wbr>char**bold again**
```

The lezer correctly parses the first line as nested `strong` tags, but it also parses the second line as nested tags, which differs from the result of CommonMark; it should be two separated `strong` tags:

```html
<p>
  <strong>
    bold-
  </strong>
  <wbr />
  char<strong>bold again
  </strong>
</p>
```

You can check CommonMark's (and other parsers') implementation [here](https://babelmark.github.io/?text=**bold-**char**bold+again**%0A%0A**bold-**%3Cwbr%3Echar**bold+again**).

Is this behavior a bug or an intended one due to the incremental nature of the parser?

**Comment by marijnh** [comment]
Seems I got the `\p{...}` categories wrong in a regexp. Attached patch should help.
