### ISSUE TITLE
Disabling SetextHeader parsing results in inconsistent parsing of HorizontalRule

### ISSUE THREAD

**Issue by ajguyot** [lezer-parser/markdown#45]
Passing `remove: ['SetextHeader']` to the MarkdownConfig successfully disables setext header parsing, however it leaves behind an inconsistency with how horizontal rules are parsed.

All three of these should produce horizontal rules: `---`, `***`, `___`. When used on lines directly below an empty line, all three of them are parsed correctly. However, when used on lines directly below text lines, only the `***` and `___` versions are parsed.

Presumably this is because the `---` version would otherwise produce a SetextHeader in this situation, but if SetextHeader parsing is disabled, then `---` should work identically to the other types of horizontal rules, including being parsed when directly below a text line.

Reproduction here: https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQgeyBtYXJrZG93biwgbWFya2Rvd25MYW5ndWFnZSB9IGZyb20gJ0Bjb2RlbWlycm9yL2xhbmctbWFya2Rvd24nOwoKY29uc3QgbWRDb25mID0gewogIHJlbW92ZTogWydTZXRleHRIZWFkaW5nJ10KfQoKbmV3IEVkaXRvclZpZXcoewogIGRvYzogIlRlc3QgKGhyIGJlbG93IGlzIG5vdCBwYXJzZWQpXG4tLS1cblxuVGVzdCAoaHIgYmVsb3cgaXMgcGFyc2VkKVxuKioqXG5cblRlc3QoaHIgYmVsb3cgaXMgcGFyc2VkKVxuX19fXG5cbi0tLVxuXldvcmtzIHdoZW4gdGhlIGxpbmUgYWJvdmUgaXMgZW1wdHlcblxuKE1pZ2h0IGhhdmUgdG8gem9vbSBpbiB0byBzZWUgdGhlIHN1YnRsZSBjb2xvciBjaGFuZ2UgdGhhdFxubWFrZXMgY2xlYXIgd2hpY2ggb2YgdGhlc2UgYXJlIGJlaW5nIHBhcnNlZCkiLAogIGV4dGVuc2lvbnM6IFtiYXNpY1NldHVwLCBtYXJrZG93bih7CiAgICBiYXNlOiBtYXJrZG93bkxhbmd1YWdlLAogICAgZXh0ZW5zaW9uczogW21kQ29uZl0KICB9KV0sCiAgcGFyZW50OiBkb2N1bWVudC5ib2R5Cn0pCg==

**Comment by marijnh** [comment]
That's an obscure use case! But I guess we should support it. Attached patch fixes this.
