### ISSUE TITLE
Allow wrapping delimiters into content wrapper

### ISSUE THREAD

**Issue by nathanlesage** [lezer-parser/markdown#48]
After finally understanding the very nice and convenient API to add small, delimited syntax tags (such as Markdown markers `==mark==`) to the parser using `ctx.addDelimiter()`, I have implemented this in various ways. However, I have one request for improvement: It would be great if we could define on the `DelimiterType` an additional element `wrapMarkers: boolean` (or similar) that dictates whether the parser wraps the delimiters themselves into the syntax node that also includes the content. This is also the behavior for, e.g., the emphasis markers that all are wrapped into their own node.

Currently, the Syntax tree looks like this:

```
Delimiter
|
+-- ContentNode
|   |
|   +-- [child nodes...]
|
Delimiter
```

It would be great if we could define a `DelimiterType` like so:

```typescript
const customDelimiter: DelimiterType = {
  resolve: 'ContentNode,
  mark: 'Delimiter',
  wrapMarkers: true
}
```

Which could result in such a tree:

```
ContentNode
|
+--+-- Delimiter
   |
   +-- [child nodes...]
   |
   +-- Delimiter
```

Thank you for your work!

**Comment by marijnh** [comment]
I'm seeing extensions like the strike-through included in the package behave the way you describe (the marks are inside of the wrapper node). Can you show what you are doing that causes this to not be the case?

**Comment by nathanlesage** [comment]
I must apologize to you. It was late yesterday, and I was seeing strange things but did not investigate properly. Indeed the delimiters are wrapped in the content node type, which I just confirmed with a clear mind. Sorry for blocking your time, it works as it should!
