### ISSUE TITLE
Potential issue with escaping pipes in tables

### ISSUE THREAD

**Issue by Monkatraz** [lezer-parser/markdown#7]
Preface: I am unsure what is actually supposed to happen with this behavior.

This is easiest to explain with my use case:

I've added some custom syntax that looks like this:
```
`js|console.log('Inline code!')`
#font sans|Here is the sans font.|#
```
As you can see, both use the pipe character.

When you use them in a table, you need to escape the pipe. This matches `markdown-it`, which I'll use as a reference because I don't have much else to go off of.
```
| | | |
| :--: | :-- | :-- |
| `` `...` `` | Monospace | `Monospaced text.`
| `` `lang\|...` ``| Inline Code | `js\|console.log('Inline code!')`
| `$...$` | Math (TeX) | $\int_{-\infty}^\infty e^{-x^2}\,dx =\sqrt{\pi}$
| `@@...@@`| Escaped | @@/This text is __escaped__, and **will only be rendered as plain text.**/@@
```

The issue arises when comparing what `markdown-it` outputs, and what Lezer outputs.
![image](https://user-images.githubusercontent.com/34875062/107974352-b3005e00-6f73-11eb-8120-9f30a75b07e6.png)
![image](https://user-images.githubusercontent.com/34875062/107974359-b8f63f00-6f73-11eb-824e-0ee3d45ed8cc.png)

The first image should have an inline code bit that looks like this:
![image](https://user-images.githubusercontent.com/34875062/107974424-cca1a580-6f73-11eb-82c0-8e7fd4ccfb4a.png)

The blue pipe character indicates that the syntax has been successfully recognized (I haven't gotten nesting working yet).

Fundamentally, the table extension "carries over" the escape character into the inline parser, when maybe it shouldn't do that, like `markdown-it`. I'm not sure what the GFM spec implies to do here, if anything. I think the root issue is with the GFM spec introducing a crummy syntax, because allowing table delimiters inside inline-spans was a fairly absurd decision. MultiMarkdown doesn't do this (and has imo entirely superior tables).

**Comment by marijnh** [comment]
I'm not aware of unescaping happening between block and inline parsing level in any other construct. For example escaped `*` characters, if they aren't found to be bullet list markers, also don't get treated as emphasis marks. Maybe there's an explicit exception in the markdown-it parser for the inline pipe syntax that allows the pipes to be escaped?

**Comment by Monkatraz** [comment]
I'm sure there is. It _may_ be worth it to copy the behavior, as otherwise any syntax using the pipe character just cannot be used inside of a table, at least without unpleasant context checks or hacks. I can see how `markdown-it`'s solution might introduce problems though, because where would the escape character _actually go?_ `markdown-it` can afford to quite literally remove the character, but Lezer has to map to the source 1:1. Replacing the slash with another character might work, but that solution feels hacky to me.

With that in mind, I think a better solution would be either:
- For me to make a MultiMarkdown table extension, and just release it
- For a configuration option to be added to the `Table` extension breaking from GFM syntax that makes it so that pipe characters are not recognized inside of inline spans (basically only characters that are direct children of the table row / cell).

I might make a PR for the latter one, if you're interested in that idea. I'm not sure how configuration would exactly work - maybe  a method on the `Table` object that `lezer-markdown` would just ignore, but allows for returning a 'configured' `Table` extension.
```ts
const ext = Table.configure({ looseDelimiters: true })
```

**Comment by marijnh** [comment]
> because where would the escape character actually go? 

There is actually a precedent for this—if you have a paragraph inside a blockquote, for example, the `>` marks are replaced by spaces before the content is passed to the inline parser.

If you can point at the markdown-it code where the table parser does the unescaping, I guess I'd be okay with having the table extension do some magic like that (though the resulting content might still confuse space-sensitive inline parsers, and creating the syntax tree for pipe characters that are both escaped at one level and part of some other construct at the next level would be a little awkward).

**Comment by Monkatraz** [comment]
I think it's [this line in `markdown-it`](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/table.js#L35). I think the code checks for an escaped pipe and "jumps" over the escape character by manipulating the current character position.

**Comment by marijnh** [comment]
I played around with this, but it got too hacky. No matter what you use as the stand-in character that replaces the backslash, it'll influence the inline parsing. (Spaces messed up the `**\|**` test from the GFM spec, because of emphasis marker whitespace rules.) The proper thing to do would be to support more complicated coordinate transformations between parsed inline content and the final tree, to allow such markers to just be hidden entirely, but I don't think I'm willing to add that level of complexity here. Since the GFM "spec" doesn't say anything about this behavior, I'm going to consider it out of scope.

(If all else fails, you could fork the table extension and add custom funky behavior.)
