### ISSUE TITLE
The link/image node does not seem to be construct

### ISSUE THREAD

**Issue by inderlef** [lezer-parser/markdown#8]
The tree hierarchy resulting from parsing an example markdown is shown below.
There is a node with a blank node type name, but I assume that there must be a link/image nodes there (Is this assumption correct?).

**Links:**
```markdown
[link](/uri "title")
```
```
+ "Document"
    + "Paragraph"
        + ""
```

**Link reference definitions:**
```markdown
[foo]: /url "title"

[foo]
```
```
+ "Document"
    + "LinkReference"
        + ""
    + "Paragraph"
        + ""
```

**Images:**
```markdown
![foo](/url "title")
```
```
+ "Document"
    + "Paragraph"
        + ""
```

Thanks for the great project.

**Comment by marijnh** [comment]
Did you look inside the unnamed node? Try using the tree's `toString` method to see what's inside it, and iteration or cursors (which automatically skip the kind of node that's confusing you here) to programatically go through its content. I'm pretty sure this is just a buffer node that you're looking at in the wrong way.

**Comment by inderlef** [comment]
Thank you. You were right.
I was able to get the node I was expecting by using the cursor.
