### ISSUE TITLE
The custom `endLeaf` function has no effect on parsing

### ISSUE THREAD

**Issue by gelprec** [lezer-parser/markdown#9]
I've been experimenting with markdown extensions these days. I have a markdown config object like this
```
 const GoodBlock = {
     defineNodes: [
         { name: "GoodBlock", block: true }, "GoodMark",
     ],
     parseBlock: [{
         name: "GoodBlock",
         parse: GoodBlockParser,
         endLeaf:(_, line) => isGoodBlock(line) >= 0,
	after: "FencedCode",
     }]
 };
 ```
 
but for me the endLeaf function has no effect on parsing. After some digging into the source code I think the problem is on line https://github.com/lezer-parser/markdown/blob/185d8665ed1bc5c6ff346ff8b59cc5d0b0c02243/src/markdown.ts#L709 

Of course, I don't have a real understanding of the source code but it seems to me that the `parser.endLeafBlock` here refer only to the `DefaultEndLeaf` array so my custom `endLeaf` function has no chance to affect the parsing.

But after replacing `parser.endLeafBlock` with `this.parser.endLeafBlock`  my `endLeaf` functions becomes active and everything seems ok. Is this correct?

**Comment by marijnh** [comment]
Right, your diagnosis seems entirely correct---that was unintentionally using the global `parser` binding. I've implemented your fix in attached patch and released 0.15.1.
